name       : xinit
version    : 1.3.4
release    : 4
source     :
    - http://xorg.freedesktop.org/releases/individual/app/xinit-1.3.4.tar.bz2 : 75d88d7397a07e01db253163b7c7a00b249b3d30e99489f2734cac9a0c7902b3
license    : GPL-3.0
component  : xorg.server
summary    : The xinit package contains a usable script to start the xserver.
builddeps  :
    - pkgconfig(x11)
description: |
    The xinit package contains a usable script to start the xserver.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
