name       : xinit
version    : 1.4.0
release    : 5
source     :
    - https://www.x.org/releases/individual/app/xinit-1.4.0.tar.gz : 17548a5df41621b87d395f1074dfb88b0dc6917f9127540b89c6de4a80f33776
license    : GPL-3.0
component  : xorg.server
summary    : The xinit package contains a usable script to start the xserver.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xorg-macros)
description: |
    The xinit package contains a usable script to start the xserver.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
