name       : xinit
version    : 1.4.1
release    : 6
source     :
    - https://www.x.org/releases/individual/app/xinit-1.4.1.tar.gz : ca33ec3de6c39589c753620e5b3bcbc8277218b949bfa2df727779b03a8d2357
license    : GPL-3.0
component  : xorg.server
summary    : The xinit package contains a usable script to start the xserver.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xorg-macros)
description: |
    The xinit package contains a usable script to start the xserver.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
